title: "Mehrdad Vasheghani Farahani"
title_separator: "-"
name: "Mehrdad Vasheghani Farahani"
description: "Researcher in Porous Media, Transport Phenomena, and Energy Systems"
url: "https://mehrdadvasheghanifarahani.github.io"

include:
  - _pages

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

markdown: kramdown
paginate: 10

author:
  name: "Mehrdad Vasheghani Farahani"
  avatar: "/assets/images/profile.jpg"
  bio: "Research Fellow in Chemical Engineering â€“ Porous Media, LBM, Energy Storage."
  location: "Manchester, UK"
