title: "Mehrdad Vasheghani Farahani"
title_separator: "-"
name: "Mehrdad Vasheghani Farahani"
description: "Researcher in Porous Media, Transport Phenomena, and Energy Systems"
url: "https://mehrdadvasheghanifarahani.github.io"

# Remote theme
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Markdown
markdown: kramdown

# Pagination
paginate: 10

# Author
author:
  name: "Mehrdad Vasheghani Farahani"
  avatar: "/assets/images/profile.jpg"
  bio: "Research Fellow in Chemical Engineering â€“ Porous Media, LBM, Energy Storage."
  location: "Manchester, UK"

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Navigation menu
main:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/
